language: rust
rust: 
  - stable
  - beta
  - nightly 
matrix: 
  allow_failures:
    - rust: nightly
  fast_finish: true
before_install:
  - sudo apt-get update
  - sudo apt-get install libz-dev
# cache: cargo
# script: 
#   - cargo test -vv --all
# env:
#   - RUST_LOG=info