language: rust
rust: 
  - stable
  - beta
  - nightly 
script:
  - cargo test --all -vv --features data_driven_tests
  - RUST_LOG=ellington,libellington=info cargo run -- -d data/
matrix: 
  allow_failures:
    - rust: nightly
  fast_finish: true
cache: 
  directories: 
    - data