[package]
name = "ellington"
version = "0.1.0"
authors = ["Adam Harries <harries.adam@gmail.com>"]
build = "build.rs"

[dependencies]
plist = "0.2"
histogram = "0.6.9"
once = "*"
byteorder = "1"
time = "*"
rayon = "1.0"
memmap = "0.6.2"
clap = "2.31.2"
flame = "0.2.2"
flamer = "^0.2.2"
rand = "0.5.2"