[package]
name = "ellington"
version = "0.1.6"
authors = ["Adam Harries <harries.adam@gmail.com>"]
build = "build.rs"
readme = "README.md"
license = "GPL-3.0-or-later"

[lib]
name = "libellington"
path = "src/lib.rs"

[[bin]]
name = "ellington"
path = "src/ellington.rs"

[dependencies]
plist = "0.2"
histogram = "0.6.9"
byteorder = "1"
clap = {version = "2.31.2", features = ["yaml"]}
rand = "0.5.2"
url = "1.7.0"
percent-encoding = "1.0.1"
serde = "1.0.66"
serde_derive= "1.0.66"
serde_json = "1.0"
regex = "1.0.1"
lazy_static = "1.0.1"
walkdir = "2"
log = "0.4"
env_logger  = "0.5.1"
commandspec = "0.10"
nom = "4.0.0"
talamel = { git = "https://github.com/AdamHarries/talamel.git" }

[build-dependencies]
commandspec = "0.10"

[features]
# This will download lots of data! 
data_driven_tests = []
extended_tests = []

[package.metadata.deb]
section = "sound"
depends = "libgcc1 (>= 1:4), libc6 (>= 2.19), id3v2, mp4v2-utils, ffmpeg"
extended-description = """\
An experimental tool for automatically calculating the BPM of audio files \
in a library of (mostly) swing music, as well as a testbed for trying out new
BPM algorithms and techniques for the above."""
